### ISSUE TITLE
DisplayTemplate for ColumnBlock is missing from templates.

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core.templates#3]

**Comment by i-love-code** [comment]
I grabbed the latest copy of the mvc web template yesterday and it was also missing a display template for the gallery block, it just rendered as a string.

I plan to commit one for it this week, unless someone gets there first.

**Comment by tidyui** [comment]
Issue has been resolved for the Blog templates in 7.0.1. Web templates will be updated in 7.0.2
