### ISSUE TITLE
Null reference exception in blog.razor when following links of categories and tags

### ISSUE THREAD

**Issue by jensbrak** [PiranhaCMS/piranha.core.templates#4]
I've only tried this using dotnet/publish and using debug in VS on Mac, but both fail the same way.

Steps to reproduce:

1. Get published piranha templates 
2. Create a new project using the razor version of the blog template 
3. Restore, build and run
4. Use seed or create blog and a blog post with categories and tags
5. Try click a link of a category or tag

`NullReferenceException: Object reference not set to an instance of an object.
Piranha.Services.PostService.GetCategoryByIdAsync(Guid id)
Piranha.Services.ArchiveService.GetByIdAsync<T>(Guid archiveId, Nullable<int> currentPage, Nullable<Guid> categoryId, Nullable<Guid> tagId, Nullable<int> year, Nullable<int> month, Nullable<int> pageSize)
RazorBlog.Pages.ArchiveModel.OnGet(Guid id, Nullable<int> year, Nullable<int> month, Nullable<int> page, Nullable<Guid> category, Nullable<Guid> tag) in Archive.cshtml.cs
+
            Data.Archive = await _api.Archives.GetByIdAsync(id, page, category, tag, year, month);
`
Or am I missing something here (quite possible, new to using Piranha and dotnet core)? I can provide more details if needed.

**Comment by tidyui** [comment]
Hi! This is a confirmed bug in which will be released in the next Service Release (https://github.com/PiranhaCMS/piranha.core/issues/801). The workaround is to enable `FullCache`.

**Comment by jensbrak** [comment]
Oh, missed that one while skimming the issues. Thx!
