### ISSUE TITLE
İmage title and alt text shown

### ISSUE THREAD

**Issue by ademsenel** [PiranhaCMS/piranha.core.templates#40]
Hi dear i build application
i upload image and i filled image metatags title and alt text
but its not show image alt text and title in web site 
you can see result in website https://www.admoteknikservis.com
version is piranha 8.4.2

best regards
Adem

**Comment by ademsenel** [comment]
hi hakan
thank you

**Comment by Pitools** [comment]
You can add a title and alternative text for the image using the properties of the model.
By editing the image block template file.
```csharp
// File: ./Views/Cms/DisplayTemplates/ImageBlock.cshtml`
<img src="@Url.Content(WebApp.Media.ResizeImage(Model, 1110))"
    title="@Model.Body.Media.Title" alt="@Model.Body.Media.AltText">
```
For version 10.0.1 this works.

**Comment by ademsenel** [comment]
Bo reason
