### ISSUE TITLE
npm install fails for new template projects

### ISSUE THREAD

**Issue by stamminator** [PiranhaCMS/piranha.core.templates#51]
After creating a new project via `dotnet new piranha.mvc`, `npm install` fails with all sorts of errors. I've tried with Node 20, 18, and 16. The gulp-sass 4 dependency seems to be the problem, as using gulp-sass 5.1.0 allows the npm install to succeed.

Between the templates' package.json being broken and the many deprecation and security warnings NPM outputs even if you do manage to get it to succeed, I think the gulpfile needs to be revisited and modernized.

**Comment by tidyui** [comment]
Yes we did an upgrade for `Piranha.Manager`, but I guess the templates were forgotten. Will add this to the next upcoming release!
