### ISSUE TITLE
TinyMCE is very simple, add more options

### ISSUE THREAD

**Issue by andreslon** [PiranhaCMS/piranha.core.templates#7]
I am trying to use these template in production but is impossible to add example code with styles using TinyMCE and not is allowed to edit the html.

![image](https://user-images.githubusercontent.com/2242679/71862316-6b987480-30c7-11ea-8d84-a1b38c1f4bf4.png)

**Comment by tidyui** [comment]
What you can do with the TinyMCE editor is totally dependent on how you configure it. The default configuration is very clean for simplicity.

See this page for reference:

http://piranhacms.org/docs/architecture/html-editors/tiny-mce
